-- MySQL Script generated by MySQL Workbench
-- Sat Nov  5 14:10:20 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema news_tracker
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `news_tracker` ;

-- -----------------------------------------------------
-- Schema news_tracker
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `news_tracker` DEFAULT CHARACTER SET utf8 ;
USE `news_tracker` ;

-- -----------------------------------------------------
-- Table `news_tracker`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news_tracker`.`company` ;

CREATE TABLE IF NOT EXISTS `news_tracker`.`company` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `root_uri` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news_tracker`.`issue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news_tracker`.`issue` ;

CREATE TABLE IF NOT EXISTS `news_tracker`.`issue` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `order_idx` (`sort_order` ASC),
  INDEX `created_at_idx` (`created_at` ASC),
  INDEX `updated_at_idx` (`updated_at` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news_tracker`.`article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `news_tracker`.`article` ;

CREATE TABLE IF NOT EXISTS `news_tracker`.`article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `title` TINYTEXT NOT NULL,
  `content` MEDIUMTEXT NOT NULL,
  `write_at` DATETIME NOT NULL,
  `uri` VARCHAR(255) NOT NULL,
  `company_id` INT NOT NULL,
  `like_count` INT NOT NULL DEFAULT 0,
  `view_count` INT NOT NULL DEFAULT 0,
  `issue_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_article_company_idx` (`company_id` ASC),
  INDEX `write_at_idx` (`write_at` ASC),
  INDEX `company_id_idx` (`company_id` ASC),
  UNIQUE INDEX `uri_UNIQUE` (`uri` ASC),
  INDEX `fk_article_issue1_idx` (`issue_id` ASC),
  CONSTRAINT `fk_article_company`
    FOREIGN KEY (`company_id`)
    REFERENCES `news_tracker`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_issue1`
    FOREIGN KEY (`issue_id`)
    REFERENCES `news_tracker`.`issue` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
